// w4_Vuex/myapp/src/views/Login.vue
<template>
    <div>
        <h1>用户登录</h1>
        <van-form @submit="onSubmit">
            <van-field
                v-model="username"
                name="username"
                label="用户名"
                :rules="rules.username"
            />
            <van-field
                v-model="password"
                type="password"
                name="password"
                label="密码"
                :rules="rules.password"
            />
            <van-field
                v-model="vcode"
                name="vcode"
                label="验证码"
                :rules="rules.vcode"
            >
                <template #extra>
                    <div
                        class="vcode"
                        v-html="vcodeSvg"
                        @click="getVcode"
                    ></div>
                </template>
            </van-field>
            <van-field name="checkbox">
                <template #input>
                    <van-checkbox
                        v-model="mdl"
                        shape="square"
                    > 下次免登录</van-checkbox>
                </template>
            </van-field>
            <div style="margin: 16px;">
                <van-button
                    block
                    type="primary"
                    native-type="submit"
                >登录</van-button>
            </div>
        </van-form>
    </div>
</template>
<script>
export default {
  name: "Login",
  data() {
    return {
      username: "",
      password: "",
      vcode: "",
      vcodeSvg: "",
      mdl: true,
      rules: {
        username: [{ required: true, message: "请填写用户名" }],
        password: [{ required: true, message: "请填写密码" }],
        vcode: [{ required: true, message: "请填写验证码" }]
      }
    };
  },
  methods: {
    async onSubmit() {
      const { data } = await this.$request.post("/login", {
        username: this.username,
        password: this.password,
        vcode: this.vcode,
        mdl:this.mdl,
      });
      if (data.code === 200) {
        // 保存用户信息到本地
        // localStorage.setItem("userInfo", JSON.stringify(data.data));
        this.login(data.data);
        const { target = "/mine" } = this.$route.query;
        this.$router.replace(target);
      } else if (data.code === 400) {
        this.$toast("验证码不正确");
      } else {
        this.$toast("用户名或密码错误");
      }
    },
    async getVcode() {
      const { data } = await this.$request.get("/vcode/picture");
      this.vcodeSvg = data.data;
    },
    login(user){
      this.$store.commit('login',user);
    }
  },
  created() {
    this.getVcode();
  }
};
</script>
<style lang='scss'>
.vcode {
  width: 111px;
  height: 40px;
  overflow: hidden;
  svg {
    height: 40px;
    transform: translateX(-20px);
  }
}
</style>
<style scoped>
</style>

// w6_Redux/src/views/Login.jsx
import React from 'react';
import {Form,Input,Checkbox,Button} from 'antd'
import request from '@/utils/request';
import './login.scss';
import store from '../store';

function Login(props) {
    const onFinish = async function(values){
        console.log('onFinish=',values);
        const data = await request.post('/login',values);
        console.log('data',data);

        if(data.code === 200){
            // localStorage.setItem('userInfo',JSON.stringify(data.data))
            store.dispatch({type:'login',user:data.data})
            props.history.push('/home');
        }
    }
    const rules = {
        username:[
            { required: true, message: '请输入用户名' }
        ],
        password:[
            { required: true, message: '请输入密码' }
        ]
    }
    return (
        <div className="login-page">
            <h1>登录H5后台管理系统</h1>
            <Form
                name="basic"
                labelCol={{ span: 8 }}
                wrapperCol={{ span: 12 }}
                initialValues={{ mdl: true }}
                onFinish={onFinish}
                // onFinishFailed={onFinishFailed}
            >
                <Form.Item
                    label="用户名"
                    name="username"
                    rules={rules.username}
                >
                    <Input />
                </Form.Item>

                <Form.Item
                    label="密码"
                    name="password"
                    rules={rules.password}
                >
                    <Input.Password />
                </Form.Item>

                <Form.Item name="mdl" valuePropName="checked" wrapperCol={{ offset: 8, span: 12 }}>
                    <Checkbox>免登录</Checkbox>
                </Form.Item>

                <Form.Item wrapperCol={{ offset: 8, span: 12 }}>
                    <Button type="primary" htmlType="submit">
                        登录
                    </Button>
                </Form.Item>
            </Form>
        </div>
    )
}

export default Login
