// w4_VueProject/manage/src/views/Login.vue
<template>
  <div class="login-page">
    <h1>用户登录</h1>
    <el-form
      :model="ruleForm"
      status-icon
      :rules="rules"
      ref="ruleForm"
      label-width="100px"
      class="demo-ruleForm"
    >
      <el-form-item
        label="用户名"
        prop="username"
      >
        <el-input
          v-model="ruleForm.username"
        ></el-input>
      </el-form-item>
      <el-form-item
        label="密码"
        prop="password"
      >
        <el-input
          type="password"
          v-model="ruleForm.password"
          autocomplete="off"
        ></el-input>
      </el-form-item>
      <el-form-item
        label="验证码"
        prop="vcode"
      >
        <el-input
          v-model="ruleForm.vcode"
        >
          <template v-slot:append>
            <div v-html="vcodeSvg"></div>
          </template>
        </el-input>
      </el-form-item>
      <el-form-item>
        <el-button
          type="primary"
          @click="submitForm"
        >登录</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>
<script>
export default {
  name: "Login",
  data() {
    return {
      ruleForm:{
        username:'',
        password:'',
        mdl:true,
        vcode:''
      },
      vcodeSvg:'',
      rules: {
        username: [{ required: true, message: "请填写用户名" }],
        password: [{ required: true, message: "请填写密码" }],
        vcode: [{ required: true, message: "请填写验证码" }]
      }
    };
  },
  methods: {
    submitForm() {
      this.$refs.ruleForm.validate(async (valid) => {
          if (valid) {
            
            // const {username,password,mdl} = this.ruleForm
            // const { data } = await this.$request.post("/login", {
            //   username,
            //   password,
            //   mdl
            // });

            const data = await this.$store.dispatch('login',this.ruleForm)
            console.log('loginData',data);
            if (data.code === 200) {
              // 保存用户信息到本地
              // this.$store.commit('login',data.data);
              
              const { target = "/manage" } = this.$route.query;
              this.$router.replace(target);
            } else if (data.code === 400) {
              this.$message({
                type:'success',
                message:"验证码不正确",
              });
            } else {
              this.$message({
                type:'error',
                message:"用户名或密码错误",
              });
            }
          } else {
            console.log('error submit!!');
            return false;
          }
        });
      
    },
    async getVcode() {
      const { data } = await this.$request.get("/vcode/picture");
      this.vcodeSvg = data.data;
    }
  },
  created() {
    this.getVcode();
  }
};
</script>
<style lang='scss'>
.login-page{
  width:500px;margin: auto;
}
.vcode {
  width: 111px;
  height: 40px;
  overflow: hidden;
  svg {
    height: 40px;
    transform: translateX(-20px);
  }
}
</style>
<style scoped>
</style>

// w6_Redux/src/views/Login.jsx
import React from 'react';
import {Form,Input,Checkbox,Button} from 'antd'
import request from '@/utils/request';
import './login.scss';
import store from '../store';

function Login(props) {
    const onFinish = async function(values){
        console.log('onFinish=',values);
        const data = await request.post('/login',values);
        console.log('data',data);

        if(data.code === 200){
            // localStorage.setItem('userInfo',JSON.stringify(data.data))
            store.dispatch({type:'login',user:data.data})
            props.history.push('/home');
        }
    }
    const rules = {
        username:[
            { required: true, message: '请输入用户名' }
        ],
        password:[
            { required: true, message: '请输入密码' }
        ]
    }
    return (
        <div className="login-page">
            <h1>登录H5后台管理系统</h1>
            <Form
                name="basic"
                labelCol={{ span: 8 }}
                wrapperCol={{ span: 12 }}
                initialValues={{ mdl: true }}
                onFinish={onFinish}
                // onFinishFailed={onFinishFailed}
            >
                <Form.Item
                    label="用户名"
                    name="username"
                    rules={rules.username}
                >
                    <Input />
                </Form.Item>

                <Form.Item
                    label="密码"
                    name="password"
                    rules={rules.password}
                >
                    <Input.Password />
                </Form.Item>

                <Form.Item name="mdl" valuePropName="checked" wrapperCol={{ offset: 8, span: 12 }}>
                    <Checkbox>免登录</Checkbox>
                </Form.Item>

                <Form.Item wrapperCol={{ offset: 8, span: 12 }}>
                    <Button type="primary" htmlType="submit">
                        登录
                    </Button>
                </Form.Item>
            </Form>
        </div>
    )
}

export default Login
